In [1]:
import numpy as np

In [24]:
a= np.array([1,2,3,4,5]) #using list
b= np.array((1,2,3,4,5)) #using tuple
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


In [25]:
#2d array
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

Checking Dimension

In [5]:
a.ndim

1

In [6]:
a1.ndim

2

In [26]:
#3d array
a2 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [9]:
#accessing 16 value
a2[1][1][3]

16

Initialize diff. types of arrays

In [27]:
a = np.zeros((2,3),dtype='int32')
a

array([[0, 0, 0],
       [0, 0, 0]])

In [28]:
b = np.ones((3,3)) #bydefault dtype = float
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.full((3,3),10)  #it will fill 10 as values

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [15]:
#identity matrix
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
#using arange; it works till n-1 thats why 21 range is given.
z= np.arange(1,21)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
#reshaping a 1D array to 2D array
z.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])