NumPy array is homogeneous data structure;
They can have dimensions like 2d , 3d.
slicing is similar to lists.

In [2]:
import numpy as np

In [24]:
a= np.array([1,2,3,4,5]) #using list
b= np.array((1,2,3,4,5)) #using tuple
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


In [25]:
#2d array
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

Checking Dimension

In [5]:
a.ndim

1

In [6]:
a1.ndim

2

In [26]:
#3d array
a2 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [9]:
#accessing 16 value
a2[1][1][3]

16

Initialize diff. types of arrays

In [17]:
a = np.zeros((2,3),dtype='int32')
a

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
b = np.ones(shape=(3,4)) #bydefault dtype = float
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.full((3,3),10)  #it will fill 10 as values

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [21]:
#identity matrix
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
#using arange; it works till n-1 thats why 21 range is given.
z= np.arange(1,21)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
#reshaping a 1D array to 2D array
z.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [3]:
#creating an array
list1 = [ 1,2,3,4]
array1 = np.array(list1)
type(array1)

numpy.ndarray

In [26]:
#2D array
list2 = [5,6,7,8]
two_d_array = np.array((list1,list2))
print (two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
#to check number and size of dimensions with shape attribute
two_d_array.shape

(2, 4)

In [7]:
#total number of items
two_d_array.size

8

In [8]:
#to check the type of data
two_d_array.dtype

dtype('int32')

In [13]:
#N = NO. OF ROWS; M = NO. OF COLUMNS; K = INDEX OF DIAGONAL(0 BY DEFAULT)
np.eye(N = 3, M = 5, k = 1, dtype = 'int32')

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [27]:
#reshaping array
np.reshape( a = two_d_array,
            newshape = (4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
#unravel multi dimensional to 1D array; C for rows, F for columns
np.ravel(a=two_d_array, order = 'C')

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
np.ravel(a=two_d_array, order = 'F')

array([1, 5, 2, 6, 3, 7, 4, 8])

In [30]:
#transposing a array using T
two_d_array.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [31]:
two_d_array + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])